baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Tommaso Sorrentino'
theme="archie"
[params]
  subtitle = 'Software Engineer'
  [params.contact]
    email = 'info@example.org'
    phone = '+1 202-555-1212'
